### ISSUE TITLE
Build with GHC 8

### ISSUE THREAD

**Issue by niteria** [JakeWheat/simple-sql-parser#11]
Currently the version bounds on `base` and `HUnit` are too strict to build with GHC 8.
After I relaxed them the package built fine. Can you relax the bounds and make a new release?

**Comment by JakeWheat** [comment]
Thanks for the report, I uploaded a fixed version.

**Comment by niteria** [comment]
Thank you! Would you consider adding `simple-sql-parser` to stackage?
