### ISSUE TITLE
GHC 8.2 compatible release

### ISSUE THREAD

**Issue by niteria** [JakeWheat/simple-sql-parser#13]
It looks like the tree builds and passes tests with GHC 8.2, but the released package won't build because of `base` bound.

Could you upload a new release?

**Comment by bergmark** [comment]
Bump since the trustee issue was filed & GHC 8.2 has been released now, any chance for an update?

**Comment by JakeWheat** [comment]
I uploaded 0.4.3 which should work with ghc 8.2.1.
