### ISSUE TITLE
cannot parser alter table statement

### ISSUE THREAD

**Issue by ChinaXing** [JakeWheat/simple-sql-parser#9]
cannot parser alter table statement.

`alter table feature_v2 add column`third_user_id`int(10) unsigned DEFAULT '0' COMMENT '第三方用户id' after`kdt_id``

**Comment by JakeWheat** [comment]
Thanks for the report. I think there are three things in the statement missing from simple-sql-parser: the 'unsigned' type modifier thing, the 'comment' part, and the 'after' part. I think these are all mysql specific right?

**Comment by ChinaXing** [comment]
yes. so the simple-sql-parser not support them ? It's better to support, because many people will need it :)

**Comment by JakeWheat** [comment]
You are correct that these are good features to support. If you want to write patches I would be happy to review/help and merge them.

**Comment by ad-si** [comment]
But `alter` itself is also missing, right?

**Comment by JakeWheat** [comment]
I think alter table is in the master branch, but not in a release yet

**Comment by ad-si** [comment]
Yeah, sorry, didn't update my comment. I'm installing the head of master now and then it's working!

**Comment by JakeWheat** [comment]
This is now in a released version, thanks for the report and comments.
